### ISSUE TITLE
Quantum Capacitor

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft#22] opened 2013-07-14 15:36 UTC
Used to store Quantum Energy

**Comment by hunterboerner** [comment] 2013-08-17 17:38
This is a block!

**Comment by sammko** [comment] 2013-10-19 17:09
moving to 1.0, our current energy network doesnt support this.

**Comment by hunterboerner** [comment] 2013-10-19 17:10
It may be possible. The block would always require energy unless full or something else needs it, probably not though.

**Comment by sammko** [comment] 2013-10-19 17:11
nope. the problem is the block would request power from itself. we need to get fokas to fix that.

**Comment by hunterboerner** [comment] 2013-10-19 17:12
@LordFokas  :+1:

**Comment by LordFokas** [comment] 2013-10-19 19:16
It requires reworking a good part of the network, but shouldn't be anything serious.
I'll be available for it as soon as I stop being pissed at BC for forcing people to lose power.

**Comment by LordFokas** [comment] 2013-11-11 00:27
Note to the implementor (probably me): Make the QuantumNet avoid setting a source location on the block in that location. This way machines will never request power from themselves, because they don't know they're a source on their network.

**Comment by sammko** [comment] 2013-11-24 12:39
Finished as of 74dab6a84423d6b8a256d7534f1ac2082eb3a400

**Comment by LordFokas** [comment] 2013-11-26 12:34
Probably not. Hook 2 capacitors together, feed one of them. Energy will probably loop between them.
They need to be sided.

**Comment by sammko** [comment] 2013-11-26 13:13
that is ture

**Comment by hunterboerner** [comment] 2013-11-28 17:50
We need to fix that loop

**Comment by hunterboerner** [comment] 2013-12-03 18:07
@LordFokas do you know how to fix this?

**Closed as completed** 2013-12-08 20:45 UTC
Labels: Feature
