### ISSUE TITLE
qdislocator Texture Error

### ISSUE THREAD

**Issue by thejereman13** [HeisenBugDev/QuantumCraft#46] opened 2013-07-28 23:01 UTC
When 2 chests are linked with the dislocator, one of the chests looses its texture. Also, the chest with no texture is no longer a valid inventory.

example: http://puu.sh/3O6ct.jpg

**Comment by hunterboerner** [comment] 2013-07-31 02:29
why is your health and food all over the place?

**Comment by thejereman13** [comment] 2013-07-31 02:50
It's a mod, I'll find the name and send you a link.

**Comment by hunterboerner** [comment] 2013-07-31 02:52
Ah, ok

**Comment by hunterboerner** [comment] 2013-07-31 02:52
Wait what, why would he have a mod installed for writing a mod if it's not needed?

**Comment by sammko** [comment] 2013-07-31 06:45
what?
i amp pretty sure he is not writing a mod

**Comment by hunterboerner** [comment] 2013-08-31 19:32
Somewhat duplicate of #34 
This will be added onto that.

**Closed as completed by hunterboerner** 2013-08-31 19:32 UTC
Labels: Bug
